Repository H-Mingle/Backend, pull requests merged in 2023-12, with the labels that each got.

#4 [FEATURE] Google OAuth2.0 로그인 URL 요청 기능 구현
  .gitignore
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/OauthController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/MingleResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/OauthLoginUrlResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/exception/ControllerAdvice.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/OauthService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/support/GoogleOauthProvider.java
  H-Mingle/src/main/java/com/hyundai/hmingle/support/OauthProvider.java
  H-Mingle/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/root-context.xml
  H-Mingle/src/main/webapp/WEB-INF/web.xml
Labels: 🚀 feature, 💛 유콩

#7 [FEATURE] 지점 채널 리스트 조회
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/ChannelController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/ChannelGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/MingleResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/post/Post.java
  H-Mingle/src/main/java/com/hyundai/hmingle/exception/ControllerAdvice.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ChannelMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ChannelService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ChannelServiceImpl.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ChannelMapper.xml
  H-Mingle/src/test/java/com/hyundai/hmingle/MapperTests.java
  H-Mingle/target/classes/com/hyundai/hmingle/HomeController.class
Labels: 🚀 feature, 💜 혜롯

#12 [FEATURE] 게시글 생성 기능 구현
  H-Mingle/pom.xml
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/PostController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/request/ImageCreateRequest.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/request/PostCreateRequest.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/PostCreateResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/PostGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/post/Image.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/post/ImageUtils.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ImageMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/PostMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ChannelServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ImageService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ImageServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostServiceImpl.java
  H-Mingle/src/main/resources/app.properties
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ImageMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/PostMapper.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/root-context.xml
  H-Mingle/src/main/webapp/WEB-INF/web.xml
  H-Mingle/src/test/java/com/hyundai/hmingle/MapperTests.java
  H-Mingle/target/m2e-wtp/web-resources/META-INF/maven/com.hyundai/hmingle/pom.properties
  H-Mingle/target/m2e-wtp/web-resources/META-INF/maven/com.hyundai/hmingle/pom.xml
  H-Mingle/target/m2e-wtp/web-resources/META-INF/maven/net.developia/H-Mingle/pom.properties
  H-Mingle/target/m2e-wtp/web-resources/META-INF/maven/net.developia/H-Mingle/pom.xml
  H-Mingle/target/m2e-wtp/web-resources/META-INF/maven/net.developia/spring02/pom.properties
  H-Mingle/target/m2e-wtp/web-resources/META-INF/maven/net.developia/spring02/pom.xml
Labels: 🚀 feature, 💜 혜롯

#15 [FEATURE] CORS 처리
  H-Mingle/src/main/java/com/hyundai/hmingle/config/WebConfiguration.java
Labels: 🚀 feature, 💛 유콩

#19 [FEATURE] Google OAuth2.0 access token 재발급 기능 구현
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/OauthController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/RefreshResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/member/Token.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/MemberMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/TokenMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/OauthService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/support/JwtTokenExtractor.java
  H-Mingle/src/main/java/com/hyundai/hmingle/support/JwtTokenProvider.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ChannelMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ImageMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/MemberMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/PostMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/TokenMapper.xml
  H-Mingle/src/main/resources/log4j.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/mybatis-config.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/root-context.xml
Labels: 🚀 feature, 💛 유콩

#21 [FEATURE] Oauth2.0 로그아웃 기능 구현
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/OauthController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/TokenMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/OauthService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/support/JwtTokenExtractor.java
  H-Mingle/src/main/java/com/hyundai/hmingle/support/JwtTokenProvider.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/TokenMapper.xml
Labels: 🚀 feature, 💛 유콩

#23 [BUG] 깨진 한글 복구
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/ChannelController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/PostController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ChannelServiceImpl.java
  H-Mingle/src/test/java/com/hyundai/hmingle/MapperTests.java
Labels: 🐞 bug, 💛 유콩, 🔧 refactor

#24 [FEATURE] 좋아요 추가&삭제 기능 구현
  H-Mingle/src/main/java/com/hyundai/hmingle/config/WebConfiguration.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/HeartController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/MemberController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/OauthController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/PostController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/request/HeartRequest.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/MemberGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/PostGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/post/Post.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/HeartMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ImageMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/MemberMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/PostMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/HeartService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/HeartServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ImageService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ImageServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/support/JwtTokenExtractor.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/HeartMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ImageMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/MemberMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/PostMapper.xml
  H-Mingle/src/main/resources/security/application-jwt.properties
  H-Mingle/src/main/resources/security/application-oauth.properties
  H-Mingle/src/main/webapp/WEB-INF/spring/root-context.xml
  H-Mingle/src/test/java/com/hyundai/hmingle/MapperTests.java
  H-Mingle/target/classes/com/hyundai/hmingle/HomeController.class
  H-Mingle/target/classes/log4j.xml
  H-Mingle/target/m2e-wtp/web-resources/META-INF/maven/com.hyundai/hmingle/pom.properties
Labels: 🚀 feature, 💜 혜롯

#27 [BUG] 잘못된 시퀀스 수정
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/MemberMapper.xml
Labels: 🐞 bug, 💛 유콩

#29 [BUG] 한글 깨짐 복구
  H-Mingle/src/main/java/com/hyundai/hmingle/support/JwtTokenExtractor.java
  H-Mingle/src/test/java/com/hyundai/hmingle/MapperTests.java
Labels: 🐞 bug, 💛 유콩

#30 [FEATURE] 게시글 댓글 작성
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/ReplyController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/request/ReplyCreateRequest.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/ReplyCreateResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/post/Post.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/post/Reply.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/MemberMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/PostMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ReplyMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/request/ReplyCreateDto.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ReplyService.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/PostMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ReplyMapper.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/mybatis-config.xml
Labels: 🚀 feature, 💛 유콩

#34 [FEATURE] 댓글 수정 구현
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/ReplyController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/request/ReplyUpdateRequest.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/ReplyUpdateResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/member/Member.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/post/Post.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/post/Reply.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/PostMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ReplyMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/request/ReplyUpdateDto.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/MemberRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/PostRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/ReplyRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ReplyService.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ReplyMapper.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/mybatis-config.xml
Labels: 🚀 feature, 💛 유콩

#37 [FEATURE] Repository 계층 분리
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/ChannelRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/HeartRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/ImageRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/MemberRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/PostRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/TokenRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ChannelServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/HeartServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ImageServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/OauthService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostServiceImpl.java
Labels: 💛 유콩, 🔧 refactor

#39 [REFACTOR] @DeleteMapping으로 변경
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/PostController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/HeartServiceImpl.java
Labels: 💜 혜롯, 🔧 refactor

#43 [FIX] 게시글 생성 쿼리문 수정
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/PostController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/request/PostCreateDto.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostServiceImpl.java
  H-Mingle/src/main/resources/app.properties
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/PostMapper.xml
  H-Mingle/src/main/webapp/WEB-INF/web.xml
Labels: 🐞 bug, 🚀 feature, 💜 혜롯

#44 [FEATURE] 댓글 삭제 구현
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/ReplyController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/post/Reply.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ReplyMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/ReplyRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ReplyService.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ReplyMapper.xml
Labels: 🚀 feature, 💛 유콩

#48 [REFACTOR] 사용자 상세정보 조회
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/MemberController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/MemberGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/member/Member.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/MemberMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/PostMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/MemberRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/PostRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberServiceImpl.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/MemberMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/PostMapper.xml
Labels: 💛 유콩, 🔧 refactor

#46 [FEATURE] 게시글 수정
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/PostController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/request/PostUpdateRequest.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ChannelMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ImageMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/PostMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/ImageRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/PostRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ImageService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ImageServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostServiceImpl.java
  H-Mingle/src/main/resources/.gitignore
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ImageMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/PostMapper.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/mybatis-config.xml
Labels: 🚀 feature, 💜 혜롯

#51 [FEATURE] 멤버 정보 수정 기능
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/MemberController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/request/MemberUpdateRequest.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/MemberMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/response/MemberUpdateResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/MemberRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberServiceImpl.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/MemberMapper.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/mybatis-config.xml
Labels: 🚀 feature, 💜 혜롯

#53 [FEATURE] 댓글 리스트 조회
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/ReplyController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/ReplyDetailResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/post/ReplyHeart.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ReplyMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/request/RepliesRequest.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/response/ReplyResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/ReplyRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ReplyService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/support/DateTimeConvertor.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ReplyMapper.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/mybatis-config.xml
Labels: 🚀 feature, 💛 유콩

#56 [FEATURE] DB properties 파일 추가
  H-Mingle/src/main/resources/.gitignore
  H-Mingle/src/main/resources/security/application-db.properties
Labels: ⚙️ config, 💛 유콩, 🔧 refactor

#58 [FEATURE] xml 에서 DB properties 파일 연결
  H-Mingle/src/main/webapp/WEB-INF/spring/root-context.xml
Labels: ⚙️ config, 💛 유콩, 🔧 refactor

#59 [FEATURE] 사용자가 작성한 게시글 리스트 조회 기능 구현
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/MyPageController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/PostController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/MyPostsResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/PostsResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ImageMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/request/MyPostRequest.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/response/MyPostResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/ImageRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MyPageService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/support/ImageConvertor.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ImageMapper.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/mybatis-config.xml
Labels: 🚀 feature, 💛 유콩

#61 [FEATURE] 게시글 리스트 조회
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/PostController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/PostListGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/PostsGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ImageMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/PostMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/request/ImagesRequest.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/response/PostResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/ImageRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/PostRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostServiceImpl.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ImageMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/PostMapper.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/mybatis-config.xml
Labels: 🚀 feature, 💜 혜롯

#63 [FEATURE] 사용자 탈퇴
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/MemberController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/MemberMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/MemberRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberServiceImpl.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/MemberMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ReplyMapper.xml
Labels: 🚀 feature, 💛 유콩

#69 [FEATURE] 댓글 리스트 조회 시 removed 가 true 인 데이터 제외
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ReplyMapper.xml
Labels: 💛 유콩, 🔧 refactor

#71 [REFACTOR] 댓글 리스트 조회 시 데이터 추가
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/ReplyController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/ReplyDetailResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/response/ReplyResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ReplyService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/support/JwtTokenExtractor.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ReplyMapper.xml
Labels: 💛 유콩, 🔧 refactor

#72 [FEATURE] 사용자가 좋아요한 게시글 리스트 조회
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/MyPageController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ImageMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/ImageRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MyPageService.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ImageMapper.xml
Labels: 🚀 feature, 💛 유콩

#74 [REFACTOR] is 포함된 변수명 수정
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/PostGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/ReplyDetailResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostServiceImpl.java
Labels: 💛 유콩, 🔧 refactor

#76 [REFACTOR] 영업점 리스트 channelId 필드 추가
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/MemberController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/ChannelGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/MemberGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/post/ImageUtils.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/MemberMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/request/ImageUpdateDto.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/MemberRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostServiceImpl.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ChannelMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/MemberMapper.xml
Labels: 💜 혜롯, 🔧 refactor

#78 [BUG] 빌드 실패 해결
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostServiceImpl.java
  H-Mingle/src/main/webapp/WEB-INF/spring/mybatis-config.xml
Labels: 🐞 bug, 💛 유콩

#79 [FEATURE] 멤버 이미지 조회&수정
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/MemberController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/PostController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/ChannelGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/MemberGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/domain/post/ImageUtils.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/MemberMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/request/ImageUpdateDto.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/MemberRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostServiceImpl.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ChannelMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/MemberMapper.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/mybatis-config.xml
Labels: 🚀 feature, 💜 혜롯

#84 [FEATURE] LocalDateTime.now() 시 타임존 설정
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/PostController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/ReplyRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostServiceImpl.java
  H-Mingle/src/main/java/com/hyundai/hmingle/support/DateTimeConvertor.java
Labels: 🐞 bug, 💛 유콩, 🔧 refactor

#87 [FEATURE] 게시글 상세 조회시 사용자 및 작성자 이미지 반환
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/PostController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/PostGetResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/PostMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/request/PostCreateDto.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/request/PostDeleteDto.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/response/PostDetailResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/PostRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostServiceImpl.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/HeartMapper.xml
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/PostMapper.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/mybatis-config.xml
Labels: 💜 혜롯, 🔧 refactor

#88 [FEATURE] 댓글 생성 시 응답값에 데이터 추가
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/ReplyCreateResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/ReplyMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/response/ReplyCreateResponseDto.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/ReplyRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/ReplyService.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/ReplyMapper.xml
  H-Mingle/src/main/resources/log4j.xml
  H-Mingle/src/main/webapp/WEB-INF/spring/mybatis-config.xml
Labels: 💛 유콩, 🔧 refactor

#93 [REFACTOR] 계층 별 역할 분리
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/MemberController.java
  H-Mingle/src/main/java/com/hyundai/hmingle/controller/dto/response/MemberUpdateResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/PostMapper.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/request/PostSidesMapperRequest.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/response/MemberUpdateMapperResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/mapper/dto/response/PostSidesMapperResponse.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/ChannelRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/MemberRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/repository/PostRepository.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/MemberService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/service/PostService.java
  H-Mingle/src/main/java/com/hyundai/hmingle/support/ImageUtils.java
  H-Mingle/src/main/resources/com/hyundai/hmingle/mapper/PostMapper.xml
Labels: 💛 유콩, 🔧 refactor
